services:
  dotnet.blazor-wasm-app:
    build:
      context: .
      dockerfile: DockerWasm/Dockerfile
    ports:
      - "7248:80"
    container_name: ctr-blazor-wasm-app
  
  dotnet.jwt-web-api:
   build:
     context: .
     dockerfile: DockerWebApi/Dockerfile
   ports:
     - "7177:8080"
   environment:
     - ASPNETCORE_ENVIRONMENT=DockerStatusEnv
   container_name: ctr-jwt-web-api
