# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_end_api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    
    - name: Restore dependencies
      run: dotnet restore ./End/DotNet.JwtWebApi/DotNet.JwtWebApi.csproj
    
    - name: Build
      run: dotnet build ./End/DotNet.JwtWebApi/DotNet.JwtWebApi.csproj --no-restore
    
  build_end_wasm:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        
        - name: Setup .NET
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: 9.0.x
        
        - name: Restore dependencies
          run: dotnet restore ./End/DotNet.BlazorWasmApp/DotNet.BlazorWasmApp.csproj
        
        - name: Build
          run: dotnet build ./End/DotNet.BlazorWasmApp/DotNet.BlazorWasmApp.csproj --no-restore

  build_start_api:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        
        - name: Setup .NET
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: 9.0.x
        
        - name: Restore dependencies
          run: dotnet restore ./Start/DotNet.JwtWebApi/DotNet.JwtWebApi.csproj
        
        - name: Build
          run: dotnet build ./Start/DotNet.JwtWebApi/DotNet.JwtWebApi.csproj --no-restore
    
  build_start_wasm:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        
        - name: Setup .NET
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: 9.0.x
        
        - name: Restore dependencies
          run: dotnet restore ./Start/DotNet.BlazorWasmApp/DotNet.BlazorWasmApp.csproj
        
        - name: Build
          run: dotnet build ./Start/DotNet.BlazorWasmApp/DotNet.BlazorWasmApp.csproj --no-restore
        